spring.application.name=whisper

server.port=8395

whisper.url=${WHISPER_URL:http://localhost:5001}
server.netty.idle-timeout=6000s
spring.mvc.async.request-timeout=6000000
###########################################
## MULTIPART (MultipartProperties)
###########################################
# Enable multipart uploads
spring.servlet.multipart.enabled=true
# Threshold after which files are written to disk.
spring.servlet.multipart.file-size-threshold=10GB
# Max file size.
spring.servlet.multipart.max-file-size=10GB
# Max Request Size
spring.servlet.multipart.max-request-size=10GB
